### ISSUE TITLE
How add jwilder nginx proxy + laravel sail

### ISSUE THREAD

**Issue by ssheduardo** [acadea/laravel-sail-nginx-php-fpm#2]
Hi,
Thanks for your work, is very good.
I use my custom docker-composer with nginx proxy (jwilder) and is perfect but I have dought how to integrate jwilder nginx proxy + laravel sail.
Some idea to integrate?

https://hub.docker.com/r/jwilder/nginx-proxy

**Comment by sam-ngu** [comment]
Sorry I'm not sure, jwilder is beyond the scope of this project.
