### ISSUE TITLE
node js

### ISSUE THREAD

**Issue by IvanSlyadnev** [acadea/laravel-sail-nginx-php-fpm#3]
how to install node js???

**Comment by asifulmamun** [comment]
I have solved this and also added the documentation, now it's pending a pull request.
**You can use this:** https://github.com/asifulmamun/contribution-laravel-sail-nginx-php-fpm

**Comment by sam-ngu** [comment]
Spin up another docker container or run node on your local machine or modify the PHP-fpm Dockerfile to install node.
